### ISSUE TITLE
advice on CN2 ebgp to DC-GW

### ISSUE THREAD

**Issue by m4w0lf** [urao/jnpr-cn2#3]
Hi Urao,
fist of all, thank you so much for the repo!
It is my bible to understand CN2

I am currently investiganting on the idea of using eBGP instead of iBGP to connect CN2 cluster to DC-GW
configuration seems to be working -> bgp sessions are up and routes got exchanged,
the only strange thing is about dynamic-tunnels: in ibgp flavour, MPLSoUDP tunnels are created, but in ebgp flavour no tunnel got created.
some time ago i was using TungstenFabric with the same paradigm without any troubles.

is there any kind of switch i have to edit in order to get tunnels working even in ebgp?

thank you and best regards,
Alex

**Comment by m4w0lf** [comment]
found!
multihop is needed...

BR
Alex

**Comment by urao** [comment]
Hi @m4w0lf ,
Glad that my repo was helpful to you.
Good to know you where able to resolve the issue. 
If interested, we can expand this repo with collaboration, if so please fork and lets expand the features supported by CN2.

Happy Holiday! 
Uma
